# Generated by Django 2.2.24 on 2022-08-30 18:11
from django.db import migrations

import phonenumbers
from phonenumbers import PhoneNumberFormat


def get_normilize_phonenumber(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(phonenumber, PhoneNumberFormat.E164)
        else:
            flat.owner_pure_phone = None
        flat.save()


def get_back(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(get_normilize_phonenumber, get_back)
    ]
