# Generated by Django 2.2.24 on 2022-08-31 22:00

from django.db import migrations


def parse_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    cached_owners = list(Owner.objects.all())
    flats = Flat.objects.all()
    cached_flats = [(flat.pk, flat.owner, flat.owner_pure_phone) for flat in flats]
    for owner in cached_owners:
        flats = [pk for pk, name, phonenumber in cached_flats if owner.name == name and owner.pure_phonenumber == phonenumber]
        owner.flat.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220831_2226'),
    ]

    operations = [
        migrations.RunPython(parse_flats_to_owner)
    ]
