# Generated by Django 2.2.24 on 2022-09-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220914_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phonenumber',
        ),
    ]
